# Generated by Django 4.0.10 on 2024-03-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_alter_currency_options_alter_currencyrates_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта'},
        ),
        migrations.AlterModelOptions(
            name='currencyrates',
            options={},
        ),
    ]
