# Generated by Django 4.0.10 on 2024-03-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0006_alter_currency_options_alter_currencyrates_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Валюта", "verbose_name_plural": "Валюты"},
        ),
        migrations.AlterModelOptions(
            name="currencyrates",
            options={
                "verbose_name": "Курс валюты",
                "verbose_name_plural": "Курсы валют",
            },
        ),
    ]
